
CREATE TRIGGER TRG_KULLANICILAR_AI ON KULLANICILAR AFTER INSERT
AS 
BEGIN
	DECLARE @KAYITNO INT
	SELECT @KAYITNO = KNO FROM inserted -- eklenen kayýt(lar)

	INSERT INTO LOG(TABLOADI, ISLEMTURU, TARIH, KAYITNO)
	VALUES('KULLANICILAR', 'YENÝ KAYIT', GETDATE(), @KAYITNO)
END
GO
