CREATE PROCEDURE SP_KULLANICCI_OLUSTUR 
	@KULLANICIADI VARCHAR(20),
	@EPOSTA VARCHAR(50)
AS
BEGIN
	DECLARE @SIFRE VARCHAR(8), @D INT, @S INT
	SET @SIFRE = ''
	SET @D = 0
	WHILE @D <= 8
	BEGIN
	   SELECT @S = ROUND(RAND() * 10,0)
	   -- üretilen sayý 10 ise 1 olarak deðiþtir
	   IF @S = 10
	   BEGIN 
	    SET @S = 1
	   END 
	   SET @SIFRE = @SIFRE + CONVERT(VARCHAR, @S)
	   SET @D = @D + 1
	END 

	INSERT INTO KULLANICILAR(KULLANICIADI, SIFRE, EPOSTA)
	VALUES(@KULLANICIADI, @SIFRE, @EPOSTA)

END
GO