
SELECT * FROM STOKLAR

SELECT MAX(GUNCELFIYAT) FROM STOKLAR

SELECT MIN(GUNCELFIYAT) FROM STOKLAR

SELECT AVG(GUNCELFIYAT) FROM STOKLAR

SELECT SUM(GUNCELFIYAT) FROM STOKLAR

SELECT GUNCELFIYAT, ROUND(GUNCELFIYAT, 0) AS YUVARLANMIS FROM STOKLAR -- 2. PARAMETRE YUVARLANDIKTAN SONRA KAÇ ONDALIKLI SAYI KALACAÐINI GÖSTERÝR
