
SELECT * FROM KULLANICILAR
SELECT * FROM LOG

-- INSERT INTO KULLANICILAR(KULLANICIADI,SIFRE,EPOSTA) VALUES('ayþe','12345','ayþe@ktu.edu.tr')

UPDATE KULLANICILAR SET SIFRE = 'yeni þifre' WHERE KNO = 2