CREATE TRIGGER TRG_STOKLAR_AI
   ON STOKLAR
   AFTER INSERT
AS
BEGIN

    DECLARE @STOKKOD VARCHAR(10)
	SELECT @STOKKOD = STOKKOD FROM inserted -- eklenen kayýt(lar)

	INSERT INTO LOG(TABLOADI, ISLEMTURU, TARIH, KAYITNO)
	VALUES('STOKLAR', 'Yeni Kayýt', GETDATE(), @STOKKOD)


END
GO