ALTER PROCEDURE SP_TEST
	@CKOD VARCHAR(20)
AS
BEGIN
	DECLARE @TTABLE TABLE
	(
	   KOD VARCHAR(10),
	   UNVAN VARCHAR(100),
	   TEDARIKCI BIT,
	   EVRAKSAYISI INT,
	   TOPLAMSATIS DECIMAL(18,2)
	   
	)

	INSERT INTO @TTABLE
	SELECT CARIKOD,CARIUNVAN, EH_TEDARIKCI,
	    dbo.FN_CARIEVRAKSAYISI(CARIKOD),
		dbo.FN_CARITOPLAMSATIS(CARIKOD)

	FROM CARI_HESAPLAR WHERE CARIKOD = @CKOD

	SELECT * FROM @TTABLE 
END
GO
