SELECT * FROM CARI_HESAPLAR
SELECT * FROM CARI_HESAP_HAREKETLERI
SELECT * FROM STOKLAR ORDER BY STOKKOD

CREATE VIEW V_CARI_HESAP_HAREKETLERI
AS
SELECT C.CARIKOD, C.CARIUNVAN, EH_TEDARIKCI,
       CH.KAYITNO, CH.EVRAKSERI, CH.EVRAKNO, CH.STOKKOD, S.STOKAD, CH.BIRIMFIYAT, CH.MIKTAR, CH.TOPLAMFIYAT,
	   CASE C.EH_TEDARIKCI WHEN 1 THEN 'Alýþ Faturasý'
	                       WHEN 0 THEN 'Satýþ Faturasý' END AS FATURATURU
 FROM CARI_HESAPLAR C INNER JOIN CARI_HESAP_HAREKETLERI CH ON C.CARIKOD = CH.CARIKOD
                      INNER JOIN STOKLAR S ON CH.STOKKOD = S.STOKKOD