SELECT *, DBO.FN_CARITOPLAMSATIS(CARIKOD) AS TOPLAMSATISTUTARI, DBO.FN_CARIEVRAKSAYISI(CARIKOD) AS EVRAKSAYISI FROM CARI_HESAPLAR

SELECT * FROM V_CARI_HESAPLAR 

SELECT * FROM STOKLAR
-- TOPLAMDA NE KADAR SATILDIÐI
SELECT SUM(MIKTAR) FROM CARI_HESAP_HAREKETLERI WHERE STOKKOD = 10018
-- KAC CARIYE SATILDIÐI
SELECT SUM(MIKTAR), COUNT(DISTINCT(CARIKOD)) FROM CARI_HESAP_HAREKETLERI WHERE STOKKOD = 10018

SELECT * FROM DBO.FN_TESTMULTI 