

SELECT *, DBO.FN_CARITOPLAMSATIS(CARIKOD) AS TOPLAMSATISTUTARI, DBO.FN_CARIEVRAKSAYISI(CARIKOD) AS EVRAKSAYISI FROM CARI_HESAPLAR

SELECT * FROM V_CARI_HESAPLAR 

SELECT SUM(TOPLAMFIYAT) FROM CARI_HESAP_HAREKETLERI WHERE CARIKOD=100

SELECT CARIKOD, COUNT(DISTINCT(EVRAKNO)) FROM CARI_HESAP_HAREKETLERI GROUP BY CARIKOD ORDER BY CARIKOD 

SELECT COUNT(DISTINCT(EVRAKNO))FROM CARI_HESAP_HAREKETLERI WHERE CARIKOD = 102