CREATE FUNCTION FN_CARITOPLAMSATIS(@CARIKOD VARCHAR(10)) 
RETURNS DECIMAL(8,2)
AS
BEGIN
	DECLARE @T DECIMAL(8,2)

	-- SET @T = (SELECT SUM(TOPLAMFIYAT) FROM CARI_HESAP_HAREKETLERI WHERE CARIKOD=@CAARIKOD)
	SELECT @T = SUM(TOPLAMFIYAT) FROM CARI_HESAP_HAREKETLERI WHERE CARIKOD=@CARIKOD

	
	RETURN @T

END
GO